name: Build SAMP Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          # Əksər yeni Android proyektləri Java 17 tələb edir. 
          # Əgər xəta versə, bunu '11' edərsən.
          java-version: '17' 

      - name: Build APK
        run: |
          # Qovluğa girməyə ehtiyac yoxdur, çünki gradlew ana qovluqdadır
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SAMP-Client-APK
          # APK birbaşa app qovluğunun içindən götürüləcək
          path: app/build/outputs/apk/**/*.apk
